include ./themes/themes/Jellybeans.conf

# Environment variables
env TERM=xterm-256color
env BROWSER=firefox

# Font settings
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0

# Window padding
window_padding_width 0

# Dynamic padding
background_opacity 1.0

# Shell
shell fish
