#---------------------------------------
#                Plugins                
#---------------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'catppuccin/tmux'
set -g @plugin 'sainnhe/tmux-fzf' # Default prefix+F
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'


#---------------------------------------
#                Theme                
#---------------------------------------
# --- Skeleton Colors ---
set -g @bg_color "#111111"
set -g @primary  "#f9de74"
set -g @active  "#f9de74"
set -g @inactive "#36342a"
set -g @inact_text "#36342a"
set -g @cwd_bg   "#f9de74"
set -g @text     "#36342a"

# --- Status Bar General ---
set -g status-style "bg=#{@bg_color},fg=#{@text}"
set -g status-left-length 50
set -g status-right-length 50

# --- Left Side: [ Icon Session ] > ---
set -g status-left "#[bg=#{@primary},fg=#{@bg_color}] 󰭹 #S #[fg=#{@primary},bg=#{@bg_color}] "

# --- Middle: Windows [ Pill Toggle Name ] > ---
setw -g window-status-current-format "#[fg=#{@active},bg=#{@bg_color}]#[fg=#{@bg_color},bg=#{@active}]   #[fg=inactive,bold]#I:#W #[fg=#{@active},bg=#{@bg_color}]"
setw -g window-status-format "#[fg=#{@inactive},bg=#{@bg_color}]#[fg=#{@primary},bg=#{@inactive}]   #I:#W #[fg=#{@inactive},bg=#{@bg_color}]"

# --- Right Side: < [ Icon Path ] ---
set -g status-right "#[fg=#{@cwd_bg},bg=#{@bg_color}]#[fg=#{@bg_color},bg=#{@cwd_bg}]  #{b:pane_current_path} "

# --- Message/Command Prompt Styles ---
set -g message-style "bg=#{@bg_color},fg=#{@primary}"
set -g message-command-style "bg=#{@bg_color},fg=#{@primary}"

set -g pane-border-style "fg=#{@inactive}"
set -g pane-active-border-style "fg=#{@primary}"

# 
set -g mode-style "fg=#{@active} bg=#{@inactive}"

#-------------------------------------------
#                Essentials                 
#-------------------------------------------
# Support colors for Alacritty
set -ga terminal-overrides ",alacritty:RGB,*256color*:smcup@:rmcup@"
# set -ga terminal-overrides ',*256color*:smcup@:rmcup@'

unbind C-b
set -g prefix F12
bind F12 send-prefix

# Start Windows & Panes @ 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Don't rename windows automatically
set-option -g allow-rename off

# Extras
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
set -g mouse on

# Copy
set-option -g set-clipboard external
# bind-T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
# bind-T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "wl-copy"

#-----------------------------------
#               Binds               
#-----------------------------------
# Split panes using | and - into CWD
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Vi
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -n C-1 send-keys C-1
bind -n C-2 send-keys C-2
bind -n C-3 send-keys C-3
bind -n C-4 send-keys C-4
bind -n C-5 send-keys C-5
bind -n C-6 send-keys C-6
bind -n C-7 send-keys C-7
bind -n C-8 send-keys C-8
bind -n C-9 send-keys C-9

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

run '~/.tmux/plugins/tpm/tpm'
