# Session
exec-once = uwsm app -s s -- dbus-update-activation-environment --systemd --all
exec-once = uwsm app -s s -- systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = uwsm app -s s -- nm-applet
exec-once = uwsm app -s s -- dunst
exec-once = uwsm app -s s -- waybar 
exec-once = [workspace 4 silent] uwsm app -s s -- 1password
exec-once = uwsm app -s s -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = uwsm app -s s -- hypridle

# Background 
exec-once = uwsm app -s b -- hyprpaper
exec-once = uwsm app -s b -- wl-paste --watch cliphist store

# Apps
exec-once = [workspace 1 silent] uwsm app -- kitty
exec-once = [workspace 2 silent] uwsm app -- firefox
exec-once = [workspace 3 silent] uwsm app -- discord
