# Session
exec-once = uwsm app -s s -- nm-applet
exec-once = uwsm app -s s -- dunst
exec-once = uwsm app -s s -- waybar 
exec-once = [workspace 4 silent] uwsm app -s s -- 1password

# Background 
exec-once = uwsm app -s b -- hyprpaper
exec-once = uwsm app -s b -- wl-paste --watch cliphist store

# Apps
exec-once = [workspace 1 silent] uwsm app -- alacritty
exec-once = [workspace 2 silent] uwsm app -- brave
exec-once = [workspace 3 silent] uwsm app -- discord
