general.import = [
  # "~/.config/alacritty/dracula.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/jellybeans.toml",
]

[env]
TERM = "alacritty"
BROWSER = "firefox"

[font]
normal = { family = "JetBrainsMono NerdFont", style = "Regular" }

[font.offset]
x = 0
y = 0

[window]
# decorations="none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[terminal]
shell = "fish"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
